[pytest]

# Это конфигурационный файл настроек запуска. 
# Тут задаются глобальные флаги (например, -v, -s), пути к папкам с тестами и регистрируются кастомные маркеры.

# Автоматически добавлять эти флаги при каждом запуске pytest
addopts = -v -s --tb=short

# Где искать тесты
testpaths = tests

# Маска для поиска файлов с тестами
python_files = test_*.py
